### PR TITLE
Table names should be lowercase

### PR DESCRIPTION
**Pull request by kevinsimard**
#2

### CODE REVIEW

**Comment by nmaquet** [comment]
Thanks for this. However, it seems that https://github.com/zendesk/maxwell/issues/362 has now been resolved, so this is no longer needed. Thanks, though!

**Comment by kevinsimard** [comment]
Ok, just not sure how this maxwell fix is fixing this repo since this is a fake generator. It's not loading the Maxwell codebase at all no?

**Comment by nmaquet** [comment]
Maxwell faker is simulating Maxwell. Maxwell was previously lowercasing column names, so the faker should have done it, too. Now, Maxwell preserves column name casing so we don't have to do anything.

**Comment by kevinsimard** [comment]
Oh ok, my bad. Got it thanks!

**Comment by nmaquet** [comment]
No worries, cheers.

**Pull request closed without merging**
